### ISSUE TITLE
Required patches to include inet-related headers on FreeBSD

### ISSUE THREAD

**Issue by yurivict** [videolabs/libmicrodns#38]
I had to apply these patches to build on FreeBSD 12.2:

```
--- include/microdns/rr.h.orig	2020-10-29 02:44:44 UTC
+++ include/microdns/rr.h
@@ -35,6 +35,8 @@
 # include <ws2tcpip.h>
 #endif
 
+#include <netinet/in.h>
+
 # ifdef __cplusplus
 extern "C" {
 # endif
--- include/utils.h.orig	2020-10-29 02:42:44 UTC
+++ include/utils.h
@@ -31,6 +31,8 @@
 #include <stdio.h>
 #include <stdint.h>
 
+#include <netinet/in.h>
+
 #include "compat.h"
 
 #define MDNS_DN_MAXSZ 256 // domain name maximum size
--- src/rr.c.orig	2020-10-29 02:40:53 UTC
+++ src/rr.c
@@ -32,6 +32,8 @@
 #include <stdlib.h>
 #include <stdint.h>
 
+#include <netinet/in.h>
+
 #include "utils.h"
 #include "microdns/microdns.h"
 #include "microdns/rr.h"
```

**Comment by jbkempf** [comment]
Sorry, but I don't see why. We're using `<arpa/inet.h>` and that should be enough for `INET*` and `inet*(`

Please provide the error log.

**Comment by yurivict** [comment]
Error messages:
```
In file included from ../src/mdns.c:38:
../include/utils.h:45:40: error: use of undeclared identifier 'IPPROTO_IP'
    return (ss_family(ss) == AF_INET ? IPPROTO_IP : IPPROTO_IPV6);
                                       ^
../include/utils.h:45:53: error: use of undeclared identifier 'IPPROTO_IPV6'
    return (ss_family(ss) == AF_INET ? IPPROTO_IP : IPPROTO_IPV6);
                                                    ^
```

This [documentation](https://pubs.opengroup.org/onlinepubs/7908799/xns/arpainet.h.html) doesn't say that ```<arpa/inet.h>``` makes the whole ```<netinet/in.h>``` available, only some parts.

The linux [manpage](https://www.man7.org/linux/man-pages/man7/ip.7.html) says that ```<netinet/in.h>``` needs to be included.

**Comment by jbkempf** [comment]
Fair enough, can you open a merge request?

**Comment by yurivict** [comment]
https://github.com/videolabs/libmicrodns/pull/50
